import express from 'express';
import path from 'path';
import { promises as fs } from 'fs';
import crypto from 'crypto';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const moduleDir = process.cwd();
const AI_ROUTER_BASE_URL = (process.env.AI_ROUTER_BASE_URL || 'https://getjobready-ai-proxy.mnijhara.workers.dev').replace(/\/$/, '');
const AI_ROUTER_MODEL = process.env.AI_ROUTER_MODEL || 'gemini-2.5-flash';
const AI_ROUTER_TIMEOUT_MS = Number(process.env.AI_ROUTER_TIMEOUT_MS || 30000);
const LEAD_WEBHOOK_URL = process.env.LEAD_WEBHOOK_URL;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const ADMIN_SESSION_SECRET = process.env.ADMIN_SESSION_SECRET || ADMIN_PASSWORD;
const TRUST_PROXY = process.env.TRUST_PROXY === 'true';
const ANALYTICS_SALT = process.env.ANALYTICS_HASH_SALT || 'hercules-analytics-v1';
const DATA_DIR = path.join(moduleDir, 'data');
const LEAD_STORE_PATH = path.join(DATA_DIR, 'leads.jsonl');
const ANALYTICS_STORE_PATH = path.join(DATA_DIR, 'analytics.jsonl');
const RATE_WINDOW_MS = 60_000;
const AI_REQUESTS_PER_WINDOW = 30;
const LEAD_REQUESTS_PER_WINDOW = 10;
const ANALYTICS_REQUESTS_PER_WINDOW = 120;
const MAX_RATE_BUCKETS = 5_000;
const rateBuckets = new Map<string, { startedAt: number; count: number }>();

function clientKey(req: express.Request, bucket: string) { return `${bucket}:${req.ip || 'unknown'}`; }
function pruneRateBuckets(now: number) { if (rateBuckets.size <= MAX_RATE_BUCKETS) return; for (const [key, bucket] of rateBuckets) if (now - bucket.startedAt >= RATE_WINDOW_MS) rateBuckets.delete(key); }
function rateLimited(req: express.Request, bucket: string, limit: number) { const key = clientKey(req, bucket); const now = Date.now(); const current = rateBuckets.get(key); if (!current || now - current.startedAt >= RATE_WINDOW_MS) { pruneRateBuckets(now); rateBuckets.set(key, { startedAt: now, count: 1 }); return false; } current.count += 1; return current.count > limit; }
function cleanText(value: unknown, maxLength: number) { return typeof value === 'string' ? value.trim().slice(0, maxLength) : ''; }
function hash(value: string) { return crypto.createHash('sha256').update(`${ANALYTICS_SALT}:${value}`).digest('hex').slice(0, 24); }
function safeReferrer(value: unknown) { try { return value ? new URL(String(value)).origin.slice(0, 160) : ''; } catch { return ''; } }
async function appendJsonl(filePath: string, value: Record<string, unknown>) { await fs.mkdir(DATA_DIR, { recursive: true, mode: 0o700 }); await fs.appendFile(filePath, JSON.stringify(value) + '\n', { encoding: 'utf8', mode: 0o600 }); }
async function readJsonl<T>(filePath: string, maxLines = 20000): Promise<T[]> { try { const raw = await fs.readFile(filePath, 'utf8'); return raw.split('\n').filter(Boolean).slice(-maxLines).flatMap((line) => { try { return [JSON.parse(line) as T]; } catch { return []; } }); } catch { return []; } }

function signAdminSession(timestamp: string) { return crypto.createHmac('sha256', ADMIN_SESSION_SECRET || '').update(timestamp).digest('hex'); }
function adminSessionValid(req: express.Request) { if (!ADMIN_PASSWORD || !ADMIN_SESSION_SECRET) return false; const raw = req.headers.cookie?.split(';').map((item) => item.trim()).find((item) => item.startsWith('hercules_admin='))?.slice('hercules_admin='.length); if (!raw) return false; const [timestamp, signature] = raw.split('.'); if (!timestamp || !signature || Date.now() - Number(timestamp) > 8 * 60 * 60 * 1000) return false; const expected = signAdminSession(timestamp); try { return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected)); } catch { return false; } }
function requireAdmin(req: express.Request, res: express.Response, next: express.NextFunction) { if (!adminSessionValid(req)) return res.status(401).json({ error: ADMIN_PASSWORD ? 'Admin authentication required' : 'Admin access is not configured' }); next(); }

async function storeLeadLocal(lead: Record<string, string>) { await appendJsonl(LEAD_STORE_PATH, { id: crypto.randomUUID(), receivedAt: new Date().toISOString(), ...lead }); }
async function callAiRouter(system: string, user: string) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), AI_ROUTER_TIMEOUT_MS); try { const response = await fetch(`${AI_ROUTER_BASE_URL}/v1/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(process.env.AI_ROUTER_API_KEY ? { Authorization: `Bearer ${process.env.AI_ROUTER_API_KEY}` } : {}) }, body: JSON.stringify({ model: AI_ROUTER_MODEL, messages: [{ role: 'system', content: system }, { role: 'user', content: user }], temperature: 0.2 }), signal: controller.signal }); if (!response.ok) throw new Error(`AI router returned ${response.status}`); const data = await response.json() as any; const content = data?.choices?.[0]?.message?.content; if (!content) throw new Error('AI router returned no content'); return String(content); } finally { clearTimeout(timeout); } }

async function startServer() {
  const app = express(); const PORT = Number(process.env.PORT || 3000); await fs.mkdir(DATA_DIR, { recursive: true, mode: 0o700 }).catch(() => undefined); app.set('trust proxy', TRUST_PROXY); app.disable('x-powered-by');
  app.use((_req, res, next) => { res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin'); res.setHeader('X-Frame-Options', 'SAMEORIGIN'); res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()'); if (process.env.NODE_ENV === 'production') { res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains'); res.setHeader('Content-Security-Policy', "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'; img-src 'self' data: https://images.unsplash.com; media-src 'self' blob: https://github.com https://objects.githubusercontent.com https://release-assets.githubusercontent.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; connect-src 'self'"); } next(); });
  app.use(express.json({ limit: '32kb' })); app.use('/api', (_req, res, next) => { res.setHeader('Cache-Control', 'no-store'); next(); });
  const getAiClient = () => { const apiKey = process.env.GEMINI_API_KEY; if (!apiKey) return null; try { return new GoogleGenAI({ apiKey }); } catch (err) { console.error('Failed to initialize GoogleGenAI client:', err); return null; } };

  app.post('/api/analytics/events', async (req, res) => { if (rateLimited(req, 'analytics', ANALYTICS_REQUESTS_PER_WINDOW)) return res.status(429).json({ error: 'Too many analytics events' }); const event = cleanText(req.body?.event, 40); const allowed = new Set(['page_view', 'cta_click', 'ai_prompt', 'calculator_interaction']); if (!allowed.has(event)) return res.status(400).json({ error: 'Unsupported analytics event' }); try { await appendJsonl(ANALYTICS_STORE_PATH, { timestamp: new Date().toISOString(), event, label: cleanText(req.body?.label, 120), path: cleanText(req.body?.path, 160).split('?')[0] || '/', session: hash(cleanText(req.body?.sessionId, 120) || `${req.ip}:${req.headers['user-agent'] || ''}`), referrer: safeReferrer(req.body?.referrer), ip: hash(req.ip || 'unknown') }); return res.status(204).end(); } catch (error) { console.error('Analytics storage error:', error); return res.status(204).end(); } });

  app.post('/api/admin/login', (req, res) => { if (!ADMIN_PASSWORD || !ADMIN_SESSION_SECRET) return res.status(503).json({ error: 'Admin access is not configured. Set ADMIN_PASSWORD and ADMIN_SESSION_SECRET in the production environment.' }); const supplied = cleanText(req.body?.password, 200); const a = Buffer.from(supplied); const b = Buffer.from(ADMIN_PASSWORD); if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return res.status(401).json({ error: 'Incorrect admin password' }); const timestamp = String(Date.now()); const value = `${timestamp}.${signAdminSession(timestamp)}`; res.setHeader('Set-Cookie', `hercules_admin=${value}; Max-Age=28800; Path=/; HttpOnly; SameSite=Lax${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`); return res.json({ ok: true }); });
  app.post('/api/admin/logout', (_req, res) => { res.setHeader('Set-Cookie', 'hercules_admin=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax'); res.status(204).end(); });
  app.get('/api/admin/overview', requireAdmin, async (_req, res) => { const [events, leads] = await Promise.all([readJsonl<any>(ANALYTICS_STORE_PATH), readJsonl<any>(LEAD_STORE_PATH)]); const cutoff = Date.now() - 30 * 24 * 60 * 60 * 1000; const recentEvents = events.filter((item) => Date.parse(item.timestamp) >= cutoff); const visits = recentEvents.filter((item) => item.event === 'page_view'); const unique = new Set(visits.map((item) => item.session)); const clicks = recentEvents.filter((item) => item.event === 'cta_click'); const ai = recentEvents.filter((item) => item.event === 'ai_prompt'); const recentLeads = leads.filter((item) => Date.parse(item.receivedAt) >= cutoff).sort((a, b) => Date.parse(b.receivedAt) - Date.parse(a.receivedAt)).slice(0, 100); const pageCounts = new Map<string, number>(); visits.forEach((item) => pageCounts.set(item.path, (pageCounts.get(item.path) || 0) + 1)); const actionCounts = new Map<string, number>(); clicks.forEach((item) => { const label = item.label || 'Untitled action'; actionCounts.set(label, (actionCounts.get(label) || 0) + 1); }); return res.json({ configured: Boolean(ADMIN_PASSWORD), metrics: { visits: visits.length, uniqueVisitors: unique.size, ctaClicks: clicks.length, aiRequests: ai.length, leads: recentLeads.length }, topPages: [...pageCounts.entries()].map(([path, count]) => ({ path, visits: count })).sort((a, b) => b.visits - a.visits).slice(0, 8), topActions: [...actionCounts.entries()].map(([label, count]) => ({ label, clicks: count })).sort((a, b) => b.clicks - a.clicks).slice(0, 10), leads: recentLeads }); });

  app.post('/api/concierge', async (req, res) => { if (rateLimited(req, 'ai', AI_REQUESTS_PER_WINDOW)) return res.status(429).json({ error: 'Too many AI requests. Please try again shortly.' }); try { const message = cleanText(req.body?.message, 4000); const context = req.body?.context && typeof req.body.context === 'object' ? req.body.context : {}; if (!message) return res.status(400).json({ error: 'Message string is required' }); const systemPrompt = `You are Hercules, the AI workforce supporting a Fractional CHRO for founders and CEOs. The Fractional CHRO owns judgement, strategy and sensitive decisions; you prepare, execute, follow up and surface what needs human attention. Be practical, concise and founder-friendly. Do not present Hercules as a compliance-only product. When legal or employment-law issues arise, flag that jurisdiction-specific professional advice may be required. End with 3 useful next actions.`; const prompt = `Founder context: ${JSON.stringify(context).slice(0, 8000)}\nFounder question: ${message}`; try { const reply = await callAiRouter(systemPrompt, prompt); return res.json({ reply, suggestions: ['Prepare this for my Fractional CHRO', 'Turn this into an HR workflow', 'Draft the message or document'] }); } catch (routerError) { console.warn('AI router unavailable, trying direct Gemini fallback:', routerError); const ai = getAiClient(); if (ai) { const response = await ai.models.generateContent({ model: 'gemini-2.5-flash', contents: `${systemPrompt}\n\n${prompt}` }); return res.json({ reply: response.text || 'Hercules is ready to assist with your HR request.', suggestions: ['Prepare this for my Fractional CHRO', 'Turn this into an HR workflow', 'Draft the message or document'] }); } throw routerError; } } catch (error) { console.error('Hercules AI Error:', error); return res.status(503).json({ error: 'AI service temporarily unavailable', reply: 'Hercules is temporarily unable to reach the AI workforce. Please try again shortly.', suggestions: ['Try again', 'Prepare this for my Fractional CHRO'] }); } });

  app.post('/api/leads', async (req, res) => { if (rateLimited(req, 'lead', LEAD_REQUESTS_PER_WINDOW)) return res.status(429).json({ error: 'Too many submissions. Please try again later.' }); const lead = { name: cleanText(req.body?.name, 120), email: cleanText(req.body?.email, 254), phone: cleanText(req.body?.phone, 40), company: cleanText(req.body?.company, 160), topic: cleanText(req.body?.topic, 200), teamSize: cleanText(req.body?.teamSize, 80), notes: cleanText(req.body?.notes, 2000), source: cleanText(req.body?.source, 80) || 'hercules-website' }; if (!lead.name || !lead.email) return res.status(400).json({ error: 'Name and email are required' }); if (!/^\S+@\S+\.\S+$/.test(lead.email)) return res.status(400).json({ error: 'Enter a valid email address' }); if (LEAD_WEBHOOK_URL) { try { const response = await fetch(LEAD_WEBHOOK_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(lead), signal: AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(`Lead webhook returned ${response.status}`); return res.status(202).json({ ok: true, delivery: 'webhook' }); } catch (error) { console.error('Lead webhook delivery failed; using local inbox fallback:', error); } } try { await storeLeadLocal(lead); return res.status(202).json({ ok: true, delivery: 'local_inbox' }); } catch (error) { console.error('Local lead storage failed:', error); return res.status(503).json({ error: 'Lead capture is temporarily unavailable. Please try again shortly.' }); } });

  app.get('/api/health', async (_req, res) => { let aiRouter = 'unreachable'; try { const response = await fetch(`${AI_ROUTER_BASE_URL}/health`, { headers: { ...(process.env.AI_ROUTER_API_KEY ? { Authorization: `Bearer ${process.env.AI_ROUTER_API_KEY}` } : {}) }, signal: AbortSignal.timeout(5000) }); aiRouter = response.ok ? 'ok' : `http_${response.status}`; } catch {} const geminiFallback = Boolean(process.env.GEMINI_API_KEY); const leadCapture = LEAD_WEBHOOK_URL ? 'webhook_configured_with_local_fallback' : 'local_inbox'; const status = aiRouter === 'ok' ? 'ok' : geminiFallback ? 'degraded' : 'unavailable'; res.status(status === 'unavailable' ? 503 : 200).json({ status, name: 'Hercules Backend API', aiRouter, aiFallback: geminiFallback ? 'configured' : 'not_configured', leadCapture, admin: ADMIN_PASSWORD ? 'configured' : 'not_configured' }); });

  if (process.env.NODE_ENV !== 'production') { const vite = await createViteServer({ server: { middlewareMode: true }, appType: 'spa' }); app.use(vite.middlewares); } else { app.use(express.static(path.join(moduleDir, 'dist'), { maxAge: '1h', index: 'index.html' })); app.get('*', (_req, res) => res.sendFile(path.join(moduleDir, 'dist', 'index.html'))); } app.listen(PORT, () => console.log(`Hercules server running on port ${PORT}`));
}
startServer().catch((error) => { console.error('Failed to start Hercules:', error); process.exit(1); });
